name: Deploy react app
on: 
  push:
    branches:
      - main
jobs:
 deploy:
  name: deploy app
  runs-on: iTerm
  strategy:
   matrix:
    node-version: [ "14.x" ]
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1 
    with:
      node-version: ${{matrix.node-version}}
    - name: install packages
      run: npm install
    - name: registry github user
      run: |
        git config --global user.email alwaysbetterpaul@gmail.com
        git config --global user.name Paul-Lazcano
    - name: deploy the app
      run: npm run deploy
      env:
          GH_TOKEN: ${{ secrets.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 }}